# -*- coding: utf-8 -*-
"""BetterInvertedIndexWC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a7dSgXLzbctpUlcfgQrcCKbRTlUUp8UM
"""

from pyspark import SparkContext
from pyspark import SparkConf
from operator import add
from tempfile import NamedTemporaryFile
from fileinput import input
from glob import glob
from tempfile import NamedTemporaryFile
from pyspark.sql import SparkSession
from pathlib import Path  
from collections import Counter 
import re
import sys
stdin = open(sys.stdin.fileno(), encoding='iso-8859-1', mode='r')

spark = SparkSession.builder.appName("BetterInvertedIndex").getOrCreate()
sc = SparkContext.getOrCreate(conf=spark)
text_rdd = sc.wholeTextFiles("hdfs://cscluster00.boisestate.edu:9000/user/kachingasilwimba/input")

def Better_inverted_index(documents):
  documents1 = documents.map(lambda x: ([(r, Path(x[0]).name) for r in x[1].split()] )).flatMap(lambda x:x).groupByKey().map(lambda x: (x[0], list(x[1])))
  documents22 = documents1.map(lambda x: (x[0], list(Counter(x[1]).items()))) 
  documents23 = documents22.mapValues(lambda x:sorted(x, key = lambda y: (-y[1], y[0])))
  print("Better Inverted Index Sucessfully Created")
  return documents23  

text_rdd2 = text_rdd.map(lambda x: (x[0], re.sub(r"[^a-zA-Z0-9\s]","",x[1])))
documents221 = Better_inverted_index(text_rdd2)
documents221.saveAsTextFile("/home/KACHINGASILWIMBA/output")